### ISSUE TITLE
Tab-complete issue in 1.13

### ISSUE THREAD

**Issue by LogGits** [filoghost/HolographicDisplays#114]
1.13 shows the holographicdisplays command tab-complete in the tab-complete list when they don't have permission to even use the command. A way to fix this is to setup a plugin.yml that includes a permission setup:
```
commands:
  start:
    description: hub of important commands.
    aliases: info
    permission: test.start

permissions:
  test.start:
    description: give access to /start
    default: op
```
This type of setup would prevent a player without access `test.start` from seeing `/start` in their tab-complete list.

**Comment by sgdc3** [comment]
@filoghost yeah, you should always define all the commands and permissions in tge plugin.yml file, so the new bukkit command system can correctly handle tab complete and permission checks.

**Comment by filoghost** [comment]
The command is only one, `/hd`, and is accessible to everyone if used without arguments. Subcommands are restricted by permissions, but I don't think they have to be listed in the plugin.yml. Am I missing something?

**Comment by LogGits** [comment]
@filoghost if you would like it to be enabled by default you can do this:
```yaml
commands:
  hd:
    description: hub of important commands.
    aliases: info
    permission: holographicdisplays.help

permissions:
  holographicdisplays.help:
    description: give access to /start
    default: true
```
This gives an option for servers who don't want non administrators seeing admin commands. If you'd like the output of /hd to still print to chat, you can always ignore the permission. This is mainly to declutter the tablist. You can manually do this via code thought this method is alot easier.
