### ISSUE TITLE
Simple online improvement

### ISSUE THREAD

**Issue by Duartteno** [filoghost/HolographicDisplays#119]
Hello, I have a lot of servers for mini games. 
```
bedwars:
  location: hub, 10.500, 100, 10.500
  lines:
  - '&aBed Wars'
  - '{online:bw-1,bw-2,bw-3,bw-4,bw-5,bw-6...} players'
```
Could you simplify it to
```
bedwars:
  location: hub, 10.500, 100, 10.500
  lines:
  - '&aBed Wars'
  - '{online:bw-*} players'
```

Thanks!
