### ISSUE TITLE
Feature request: Permission-based holograms

### ISSUE THREAD

**Issue by SlimeDog** [filoghost/HolographicDisplays#232]
I would like a configurable option to display a specific hologram to a player only if they have a specific permission. Use case: Different groups could see different holograms (or none at all).

The permission could be defined in the hologram node (for example)
```
city_spawn:
  location: world_city, -558.5, 68.206, 79.5
  lines:
  - ' &aWelcome to The City. '
  - ' &aVisit the restaurant in the office tower. '
  - ' &7Right-click Jack to learn about his world. '
  view-permission: holograms.view.city_spawn
```
or it could be on the hologram node id (same example)
> holograms.view._city_spawn_
