### ISSUE TITLE
Individual holograms not hiding from other players when they join after (you)

### ISSUE THREAD

**Issue by mechoriet** [filoghost/HolographicDisplays#304]
### Description
holograms are stacking up while using HolographicDisplays 2.4.3 with ProtocolLib 4.5.1 on 1.8.8

![image](https://user-images.githubusercontent.com/4313219/86520252-7f3c5200-be42-11ea-90ac-6793fe8d7c0a.png)

```java
final Player p = user.getPlayer();
final List<Hologram> list = Lists.newArrayList();

for ( Location loc : hologramLocations )
{
    Hologram hologram = HologramsAPI.createHologram( SkyWars.getInstance(), loc );
    VisibilityManager vm = hologram.getVisibilityManager();

    vm.showTo( p );
    vm.setVisibleByDefault( false );

    for ( String line : lines ) // lines come from a config
    {
        line = format( user, line ); //does this placeholder to data conversion
        hologram.appendTextLine( line );
    }
    list.add( hologram );
}
holograms.put( user.getName(), list );
```
it maybe seems like when they get in entity activation distance
it gets shown to everyone instead of only that player that was set via the ```vm.showTo( p );``` possibly

### Platform

- Server version (output of `/version`): 1.8.8
- Holographic Displays version (check with `/hd`): 2.4.3
- ProtocolLib version, if installed (check with `/protocol version`): 4.5.1
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): ViaVersion-3.0.1 

### Additional context

maybe some usefull information
```yaml
    entity-activation-range:
      animals: 32
      monsters: 32
      misc: 16
    entity-tracking-range:
      players: 64
      animals: 10
      monsters: 10
      misc: 16
      other: 24
```
