### ISSUE TITLE
Can I Use Headdatabase On Floating Items?

### ISSUE THREAD

**Issue by Inxity** [filoghost/HolographicDisplays#358]
### What are you trying to do?

I want to use custom player heads in floating items on HeadDatabase plugin

### What have you tried so far?

I didnt try anything because i dont know how to

### Platform

- Server version (output of `/version`): Paper version git-Paper-246 (MC: 1.16.3)
- Holographic Displays version (check with `/hd`): v2.4.5
- ProtocolLib version, if installed (check with `/protocol version`): ProtocolLib v4.6.0-SNAPSHOT-b483
- Do you use plugins to allow players to join with multiple Minecraft versions (such as ViaVersion, ProtocolSupport, ...): No

**Comment by Drago903** [comment]
I think this may be in the suggestion class

**Comment by filoghost** [comment]
You already can, if you know how to use NBT data: https://filoghost.me/docs/holographic-displays/icons (last section)

**Comment by SlimeDog** [comment]
I have tried, for example
```
lobby-lucky:
  location: world_lobby, 142.25, 6.4, 134.0
  lines:
  - '&e&lLUCKYBLOCK'
  - 'ICON: player_head {display:{Name:"{\"text\":\"Lucky Block (black)\"}"},SkullOwner:{Id:"9b5fbbce-527a-4958-b625-d288e0914326",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzdiMTg3ZTM4YjQwN2ZlYWJhZjE5MDg3OWQ5OGE2N2Y0YzcwNTJmMzIwMWY3MmU0NDU3MWY1MzdlYTg5ZDRjNyJ9fX0="}]}}}'
```
based on this head: https://minecraft-heads.com/custom/decoration/44208-lucky-block-black

It displays the default player head. Obviously, I am not getting the NBT right. Please advise.
